// students
export const students = [
  {
    id: 1,
    firstname: 'folarin',
    lastname: 'salami',
    email: 'salamifolarin1410@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'backend',
  },
  {
    id: 2,
    firstname: 'elizabeth',
    lastname: 'oladei',
    email: 'hellomojisolalizzy@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'cloud',
  },
  {
    id: 3,
    firstname: 'love',
    lastname: 'ugbodaga',
    email: 'lovecynthiau@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'frontend',
  },
  {
    id: 4,
    firstname: 'abigael',
    lastname: 'anyanwu',
    email: 'abigaelanyanwu@gmail.com',
    gender: 'female',
    age: 20,
    tracks: 'frontend',
  },
  {
    id: 5,
    firstname: 'adetola',
    lastname: 'adeya',
    email: 'detolaadeya@gmail.com',
    gender: 'female',
    age: 33,
    tracks: 'cloud',
  },
  {
    id: 6,
    firstname: 'adetayo',
    lastname: 'akinsanya',
    email: 'akinsanyaadetayo@gmail.com',
    gender: 'male',
    age: 30,
    tracks: 'cloud',
  },
  {
    id: 7,
    firstname: 'silver',
    lastname: 'ekandem',
    email: 'silvernnaokonkwo@gmail.com',
    gender: 'female',
    age: 34,
    tracks: 'frontend',
  },
  {
    id: 8,
    firstname: 'morenikeji',
    lastname: 'bello',
    email: 'bellokeji19@gmail.com',
    gender: 'male',
    age: 37,
    tracks: 'backend',
  },
  {
    id: 9,
    firstname: 'oluwaseun',
    lastname: 'awosise',
    email: 'awosiseo@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'backend',
  },
  {
    id: 10,
    firstname: 'tunde',
    lastname: 'wey',
    email: 'tundepeter01@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'backend',
  },
  {
    id: 11,
    firstname: 'temitope',
    lastname: 'oluwabunmi',
    email: 'toluwabunmi9@gmail.com',
    gender: 'cloud',
    age: 26,
    tracks: 'cloud',
  },
  {
    id: 12,
    firstname: 'anthonia',
    lastname: 'nwanya',
    email: 'tonianwanya@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'frontend',
  },
  {
    id: 13,
    firstname: 'nkemelu',
    lastname: 'adaeze',
    email: 'nkemelufaith@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 14,
    firstname: 'sarah',
    lastname: 'daniel',
    email: 'sarahpdaniel@outlook.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 15,
    firstname: 'taofeek',
    lastname: 'ogungbade',
    email: 'taohphyk@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'cloud',
  },
  {
    id: 16,
    firstname: 'emmanuel',
    lastname: 'amoo',
    email: 'amooemma10@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 17,
    firstname: 'busayo',
    lastname: 'akinseye',
    email: 'akinseyebusayo86@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 18,
    firstname: 'sandra',
    lastname: 'omage',
    email: 'magesandra270@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'frontend',
  },
  {
    id: 19,
    firstname: 'abiola',
    lastname: 'ayodele',
    email: 'ayodelaustinab@gmail.com',
    gender: 'male',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 20,
    firstname: 'sideeq',
    lastname: 'ishola',
    email: 'isholasideeq@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 21,
    firstname: 'anthony',
    lastname: 'onah',
    email: 'anthonyonah18@gmail.com',
    gender: 'male',
    age: 21,
    tracks: 'cloud',
  },
  {
    id: 22,
    firstname: 'victor',
    lastname: 'onyekwere',
    email: 'fgod547@gmail.com',
    gender: 'male',
    age: 28,
    tracks: 'cloud',
  },
  {
    id: 23,
    firstname: 'eegunjobi',
    lastname: 'adeolu',
    email: 'victoreegunjobi@yahoo.com',
    gender: 'male',
    age: 24,
    tracks: 'cloud',
  },
  {
    id: 24,
    firstname: 'francis',
    lastname: 'jeremiah',
    email: 'cyberspades.tech@gmail.com',
    gender: 'male',
    age: 27,
    tracks: 'cloud',
  },
  {
    id: 25,
    firstname: 'jeremiah',
    lastname: 'ojonuba',
    email: 'ojonuba93@gmail.com',
    gender: 'male',
    age: 26,
    tracks: 'backend',
  },
  {
    id: 26,
    firstname: 'ahmad',
    lastname: 'tahir',
    email: 'aztahir20@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 27,
    firstname: 'moyinoluwa',
    lastname: 'awoo',
    email: 'amooadedunmola@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 28,
    firstname: 'moyinoluwa',
    lastname: 'awoo',
    email: 'amooadedunmola@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 29,
    firstname: 'maryvenia',
    lastname: 'okoye',
    email: 'maryveniapoop@gmail.com',
    gender: 'female',
    age: 26,
    tracks: 'cloud',
  },
  {
    id: 30,
    firstname: 'chinaza',
    lastname: 'onwumechuru',
    email: 'chinaza.judith96@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 31,
    firstname: 'enajevwe',
    lastname: 'ejokirhie',
    email: 'enasamuel1@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'cloud',
  },
  {
    id: 32,
    firstname: 'chinedu',
    lastname: 'agu',
    email: 'chineduchristopher151292@gmail.com',
    gender: 'male',
    age: 28,
    tracks: 'frontend',
  },
  {
    id: 33,
    firstname: 'mujidat',
    lastname: 'olowa',
    email: 'mujeedaholowa@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 34,
    firstname: 'mujidat',
    lastname: 'olowa',
    email: 'mujeedaholowa@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 35,
    firstname: 'destiny',
    lastname: 'obirije',
    email: 'obirijedestiny@gmail.com',
    gender: 'female',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 36,
    firstname: 'amara',
    lastname: 'egbuna',
    email: 'egbunajoanna16@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'frontend',
  },
  {
    id: 37,
    firstname: 'chidinma',
    lastname: 'onyia',
    email: 'chidinmaedna@gmail.com',
    gender: 'female',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 38,
    firstname: 'kingsley',
    lastname: 'umujeyan',
    email: 'kingsleyumujeyan@gmail.com',
    gender: 'male',
    age: 41,
    tracks: 'frontend',
  },
  {
    id: 39,
    firstname: 'oluchi',
    lastname: 'ogwuegbu',
    email: 'oluchiogwuegbu@gmail.com',
    gender: 'female',
    age: 41,
    tracks: 'frontend',
  },
  {
    id: 40,
    firstname: 'olasunkanmi',
    lastname: 'ogunnubi',
    email: 'olasunkanmiogunnubi@yahoo.com',
    gender: 'male',
    age: 35,
    tracks: 'frontend',
  },
  {
    id: 41,
    firstname: 'Edna',
    lastname: 'Onyia',
    email: 'chidinmaedna@gmail.com',
    gender: 'female',
    age: 30,
    tracks: 'frontend',
  },
   {
    id: 42,
    firstname: 'olusola',
    lastname: 'bakare',
    email: 'gloryproducer@gmail.com',
    gender: 'male',
    role: 'cloud'
  }
  },
]

// Tutors
export const tutors = [
  {
    id: 1,
    firstname: 'oluwasetemi',
    lastname: 'ojo',
    email: 'setemi@altschoolafrica.com',
    gender: 'male',
    role: 'frontend instructor'
  },
]
