// students
export const students = [
  {
    id: 1,
    firstname: 'folarin',
    lastname: 'salami',
    email: 'salamifolarin1410@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'backend',
  },
  {
    id: 2,
    firstname: 'elizabeth',
    lastname: 'oladei',
    email: 'hellomojisolalizzy@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'cloud',
  },
  {
    id: 3,
    firstname: 'love',
    lastname: 'ugbodaga',
    email: 'lovecynthiau@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'frontend',
  },
  {
    id: 4,
    firstname: 'abigael',
    lastname: 'anyanwu',
    email: 'abigaelanyanwu@gmail.com',
    gender: 'female',
    age: 20,
    tracks: 'frontend',
  },
  {
    id: 5,
    firstname: 'adetola',
    lastname: 'adeya',
    email: 'detolaadeya@gmail.com',
    gender: 'female',
    age: 33,
    tracks: 'cloud',
  },
  {
    id: 6,
    firstname: 'adetayo',
    lastname: 'akinsanya',
    email: 'akinsanyaadetayo@gmail.com',
    gender: 'male',
    age: 30,
    tracks: 'cloud',
  },
  {
    id: 7,
    firstname: 'silver',
    lastname: 'ekandem',
    email: 'silvernnaokonkwo@gmail.com',
    gender: 'female',
    age: 34,
    tracks: 'frontend',
  },
  {
    id: 8,
    firstname: 'morenikeji',
    lastname: 'bello',
    email: 'bellokeji19@gmail.com',
    gender: 'male',
    age: 37,
    tracks: 'backend',
  },
  {
    id: 9,
    firstname: 'oluwaseun',
    lastname: 'awosise',
    email: 'awosiseo@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'backend',
  },
  {
    id: 10,
    firstname: 'tunde',
    lastname: 'wey',
    email: 'tundepeter01@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'backend',
  },
  {
    id: 11,
    firstname: 'temitope',
    lastname: 'oluwabunmi',
    email: 'toluwabunmi9@gmail.com',
    gender: 'cloud',
    age: 26,
    tracks: 'cloud',
  },
  {
    id: 12,
    firstname: 'anthonia',
    lastname: 'nwanya',
    email: 'tonianwanya@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'frontend',
  },
  {
    id: 13,
    firstname: 'nkemelu',
    lastname: 'adaeze',
    email: 'nkemelufaith@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 14,
    firstname: 'sarah',
    lastname: 'daniel',
    email: 'sarahpdaniel@outlook.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 15,
    firstname: 'taofeek',
    lastname: 'ogungbade',
    email: 'taohphyk@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'cloud',
  },
  {
    id: 16,
    firstname: 'emmanuel',
    lastname: 'amoo',
    email: 'amooemma10@gmail.com',
    gender: 'male',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 17,
    firstname: 'busayo',
    lastname: 'akinseye',
    email: 'akinseyebusayo86@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 18,
    firstname: 'sandra',
    lastname: 'omage',
    email: 'magesandra270@gmail.com',
    gender: 'female',
    age: 22,
    tracks: 'frontend',
  },
  {
    id: 19,
    firstname: 'abiola',
    lastname: 'ayodele',
    email: 'ayodelaustinab@gmail.com',
    gender: 'male',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 20,
    firstname: 'sideeq',
    lastname: 'ishola',
    email: 'isholasideeq@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 21,
    firstname: 'anthony',
    lastname: 'onah',
    email: 'anthonyonah18@gmail.com',
    gender: 'male',
    age: 21,
    tracks: 'cloud',
  },
  {
    id: 22,
    firstname: 'victor',
    lastname: 'onyekwere',
    email: 'fgod547@gmail.com',
    gender: 'male',
    age: 28,
    tracks: 'cloud',
  },
  {
    id: 23,
    firstname: 'eegunjobi',
    lastname: 'adeolu',
    email: 'victoreegunjobi@yahoo.com',
    gender: 'male',
    age: 24,
    tracks: 'cloud',
  },
  {
    id: 24,
    firstname: 'francis',
    lastname: 'jeremiah',
    email: 'cyberspades.tech@gmail.com',
    gender: 'male',
    age: 27,
    tracks: 'cloud',
  },
  {
    id: 25,
    firstname: 'jeremiah',
    lastname: 'ojonuba',
    email: 'ojonuba93@gmail.com',
    gender: 'male',
    age: 26,
    tracks: 'backend',
  },
  {
    id: 26,
    firstname: 'ahmad',
    lastname: 'tahir',
    email: 'aztahir20@gmail.com',
    gender: 'male',
    age: 23,
    tracks: 'frontend',
  },
  {
    id: 27,
    firstname: 'moyinoluwa',
    lastname: 'awoo',
    email: 'amooadedunmola@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 28,
    firstname: 'moyinoluwa',
    lastname: 'awoo',
    email: 'amooadedunmola@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 29,
    firstname: 'maryvenia',
    lastname: 'okoye',
    email: 'maryveniapoop@gmail.com',
    gender: 'female',
    age: 26,
    tracks: 'cloud',
  },
  {
    id: 30,
    firstname: 'chinaza',
    lastname: 'onwumechuru',
    email: 'chinaza.judith96@gmail.com',
    gender: 'female',
    age: 23,
    tracks: 'cloud',
  },
  {
    id: 31,
    firstname: 'enajevwe',
    lastname: 'ejokirhie',
    email: 'enasamuel1@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'cloud',
  },
  {
    id: 32,
    firstname: 'chinedu',
    lastname: 'agu',
    email: 'chineduchristopher151292@gmail.com',
    gender: 'male',
    age: 28,
    tracks: 'frontend',
  },
  {
    id: 33,
    firstname: 'mujidat',
    lastname: 'olowa',
    email: 'mujeedaholowa@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 34,
    firstname: 'mujidat',
    lastname: 'olowa',
    email: 'mujeedaholowa@gmail.com',
    gender: 'female',
    age: 27,
    tracks: 'frontend',
  },
  {
    id: 35,
    firstname: 'destiny',
    lastname: 'obirije',
    email: 'obirijedestiny@gmail.com',
    gender: 'female',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 36,
    firstname: 'amara',
    lastname: 'egbuna',
    email: 'egbunajoanna16@gmail.com',
    gender: 'female',
    age: 25,
    tracks: 'frontend',
  },
  {
    id: 37,
    firstname: 'chidinma',
    lastname: 'onyia',
    email: 'chidinmaedna@gmail.com',
    gender: 'female',
    age: 24,
    tracks: 'frontend',
  },
  {
    id: 38,
    firstname: 'kingsley',
    lastname: 'umujeyan',
    email: 'kingsleyumujeyan@gmail.com',
    gender: 'male',
    age: 41,
    tracks: 'frontend',
  },
  {
    id: 39,
    firstname: 'oluchi',
    lastname: 'ogwuegbu',
    email: 'oluchiogwuegbu@gmail.com',
    gender: 'female',
    age: 41,
    tracks: 'frontend',
  },
  {
    id: 40,
    firstname: 'olasunkanmi',
    lastname: 'ogunnubi',
    email: 'olasunkanmiogunnubi@yahoo.com',
    gender: 'male',
    age: 35,
    tracks: 'frontend',
  },
  {
    id: 41,
    firstname: 'Edna',
    lastname: 'Onyia',
    email: 'chidinmaedna@gmail.com',
    gender: 'female',
    age: 30,
    tracks: 'frontend',
  },
  {
    id: 42,
    firstname: 'olusola',
    lastname: 'bakare',
    email: 'gloryproducer@gmail.com',
    gender: 'male',
    age: 25,
    tracks: 'cloud',
  },
  {
    id: 43,
    firstname: 'abba',
    lastname: 'jibril',
    email: 'jibrilabbasani@gmail.com',
    gender: 'male',
    age: 27,
    tracks: 'cloud'
  },
  {
    id: 44,
    firstname: 'ogochukwu',
    lastname: 'Eze',
    email: 'ogoeze@aol.com',
    gender: 'non-binary',
    age: 49,
    tracks: 'frontend',  
  },
  {
    id: 45,
    firstname: 'Olorunfunmi',
    lastname: 'Ajao',
    email: 'funmiajao@hotmail.com',
    gender: 'trans',
    age: 20,
    tracks: 'frontend',
  },
  {
    id: 46,
    firstname: 'Oghenekome',
    lastname: 'Avbioro',
    email: 'komeboy007@gmail.com',
    gender: 'male',
    age: 28,
    tracks: 'cloud',
  },
  {
    id: 47,
    firstname: 'Nguavese',
    lastname: 'Omoche',
    email: 'chechevese@yahoo.com',
    gender: 'female',
    age: 40,
    tracks: 'backend',    
  },
  {
    id: 48,
    firstname: 'Ololade',
    lastname: 'Alade',
    email: 'ladealade@gmail.com',
    gender: 'female',
    age: 31,
    tracks: 'backend',
  },
  {
    id: 49,
    firstname: 'Mfonobong',
    lastname: 'Ikpe',
    email: 'mfon.ikpe@hotmail.com',
    gender: 'male',
    age: 37,
    tracks: 'frontend',
  },
  {
    id: 50,
    firstname: 'Oluwatobi',
    lastname: 'Meseko',
    email: 'tobimexico@yahoo.com',
    gender: 'male',
    age: 19,
    tracks: 'cloud',
  },
  {
    id: 51,
    firstname: 'Balarabe',
    lastname: 'Danladi',
    email: 'balaladi@gmail.com',
    gender: 'male',
    age: 39,
    tracks: 'frontend',    
  },
  {
    id: 52,
    firstname: 'Ibinabo',
    lastname: 'George',
    email: 'binageorge@outlook.com',
    gender: 'female',
    age: 33,
    tracks: 'cloud',    
  },
  {
    id: 53,
    firstname: 'Peterside',
    lastname: 'Briggs',
    email: 'peter.briggs@yahoo.com',
    gender: 'male',
    age: 45,
    tracks: 'backend',
  },
  {
    id: 54,
    firstname: 'Ibukun',
    lastname: 'Aderibigbe',
    email: 'ibk4ade@gmail.com',
    gender: 'female',
    age: 34,
    tracks: 'cloud',
  },
  {
    id: 55,
    firstname: 'Ochuko',
    lastname: 'Efemuaye',
    email: 'efechuko@gmail.com',
    gender: 'female',
    age: 31,
    tracks: 'cloud',
  },
  {
    id: 56,
    firstname: 'Ijeoma',
    lastname: 'Mbagwu',
    email: 'ijeoma.mbagwu@gmail.com',
    gender: 'female',
    age: 45,
    tracks: 'frontend',
  },
  {
    id: 57,
    firstname: 'Nikita',
    lastname: 'Ubah',
    email: 'nikitaubah@hotmail.com',
    gender: 'female',
    age: 24,
    tracks: 'cloud',
  },
    {
      id: 58,
      firstname: 'Folashade',
      lastname: 'Jinadu',
      email: 'folajinadu@yahoo.com',
      gender: 'female',
      age: 29,
      tracks: 'frontend',
    },
  {
    id: 59,
    firstname: 'Afolabi',
    lastname: 'Afolayan',
    email: 'folafolayan@gmail.com',
    gender: 'male',
    age: 30,
    tracks: 'backend',
  },
  {
    id: 60,
    firstname: 'Nwanneka',
    lastname: 'Oluyemi',
    email: 'nnekaoluyemi@hotmail.com',
    gender: 'non-binary',
    age: 22,
    tracks: 'backend',
  },
  {
    id: 61,
    firstname: 'Adaeze',
    lastname: 'Abia',
    email: 'adaezeabia@gmail.com',
    gender: 'female',
    age: 33,
    tracks: 'frontend',    
  },
  {
    id: 62,
    firstname: 'Abass',
    lastname: 'Lawrence',
    email: 'abasslaw@gmail.com',
    gender: 'male',
    age: 50,
    tracks: 'cloud',
  },
  {
    id: 63,
    firstname: 'Chidinma',
    lastname: 'Ojukwu',
    email: 'chidiojukwu@yahoo.com',
    gender: 'female',
    age: 34,
    tracks: 'frontend',
  },
  {
    id: 64,
    firstname: 'Nasir',
    lastname: 'Alli',
    email: 'nasir4life@hotmail.com',
    gender: 'male',
    age: 30,
    tracks: 'cloud',
  },
  {
    id: 65,
    firstname: 'Kelechi',
    lastname: 'Amadi',
    email: 'keleamadi@gmail.com',
    gender: 'female',
    age: 45,
    tracks: 'frontend',
  },
  {
    id: 66,
    firstname: 'Olarewaju',
    lastname: 'Olaniyi',
    email: 'lareolaniyi@gmail.com',
    gender: 'male',
    age: 36,
    tracks: 'backend',
  },
  {
    id: 67,
    firstname: 'Olumide',
    lastname: 'Aina',
    email: 'mideaina@yahoo.com',
    gender: 'female',
    age: 34,
    tracks: 'frontend',
  },
  {
    id: 68,
    firstname: 'Tejiri',
    lastname: 'Ighodaro',
    email: 'jiridaro@yahoo.com',
    gender: 'female',
    age: 29,
    tracks: 'frontend',
  },
  {
    id: 69,
    firstname: 'Obinna',
    lastname: 'Falade',
    email: 'obifalade@yahoo.com',
    gender: 'male',
    age: 27,
    tracks: 'cloud',
  },
  {
    id: 70,
    firstname: 'Alyssia',
    lastname: 'Okojie',
    email: 'alyokojie@gmail.com',
    gender: 'female',
    age: 33,
    tracks: 'cloud',
  },
]

// Tutors
export const tutors = [
  {
    id: 1,
    firstname: 'oluwasetemi',
    lastname: 'ojo',
    email: 'setemi@altschoolafrica.com',
    gender: 'male',
    role: 'frontend instructor',
  },
  {
    id: 2,
    firstname: 'abubakar',
    lastname: 'ango',
    email: 'abubakarsaddiqango@gmail.com',
    gender: 'male',
    role: 'cloud instructor',
  },
  {
    id: 3,
    firstname: 'rukevwe',
    lastname: 'onuwa',
    email: '',
    gender: 'female',
    role:'associate program manager'
  },
  {
    id: 4,
    firstname: 'jerry',
    lastname: 'uke',
    email: 'jerry@altschoolafrica.com',
    gender: 'male',
    role: 'workspace admin'
  },
  {
    id: 5,
    firstname: 'racheal',
    lastname: 'onoja',
    email: 'rachael@altschoolafrica.com',
    gender: 'female',
    role: 'director of learning'
  },
  {
    id: 6,
    firstname:'tabitha',
    lastname:'kavyu',
    email: 'tabitha@altschoolafrica.com',
    gender: 'female',
    role: 'community manager'
  }
]
